version: '{build}'
branches:
  only:
  - master
configuration: Release
init:
- ps: Update-AppveyorBuild -Version "1.0.$env:appveyor_build_number.$(Get-Date -format yyMMdd)"
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
artifact:
- path: '**\*.dll'
- path: '**\*.pdb'