version: '{build}'
branches:
  only:
  - master
configuration: Release
init:
- ps: Update-AppveyorBuild -Version "1.0.$env:appveyor_build_number.$(([datetime](Get-Date) - [datetime]'2000-01-01').Days)"
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
  publish_nuget: true
artifacts:
- path: 'src\**\bin\**\Velyo.AspNet.Markdown.dll'
- path: 'src\**\bin\**\Velyo.AspNet.Markdown.pdb'
nuget:
  account_feed: true
deploy:
- provider: NuGet
  api_key:
    secure: pi98jdOOgUknVbO9zAh2LJiCCsc48HRZ3sGMvCX7DbkeBglS/T1gPcpGee9oOvqO
  artifact: /.*\.nupkg/
# on:
# appveyor_repo_tag: true # deploy on tag push only